defaults:
  - _self_
  - eval_codes: "embed_200_6b50c7179bf6"

#This defines the index times to create task dfs from
index_hash: 7573f855c4b050a9d79d57fefd8a139c

paths:
  index_times_dir: /users/gbk2114/eq_stuff/tasks/eval/index_times/${index_hash}/held_out
  all_tasks_dir: /users/gbk2114/eq_stuff/tasks/all/held_out
  out_root_dir: /users/gbk2114/eq_stuff/tasks/eval/tasks_from_index

skip_existing: false
