defaults:
  - _self_
  - eval_codes: 10000_ID__8db2be6fadf8

#This defines the index times to create task dfs from
index_hash: 7573f855c4b050a9d79d57fefd8a139c

# Durations (in days) to generate eval tasks for
durations: [30, 60, 90, 180, 365, 731]

paths:
  index_times_dir: /users/gbk2114/eq_stuff/tasks/eval/index_times/${index_hash}/held_out
  task_dir_base: /users/gbk2114/eq_stuff/tasks
  out_root_dir: /users/gbk2114/eq_stuff/tasks/eval/tasks_from_index_new

skip_existing: false
