defaults:
  - _self_

# inputs
model_run_dir: ${oc.env:OUTPUT_DIR}/outputs/2026-01-03/15-43-49/
task_df_fp: ${oc.env:TASK_DIR}/eval/aces/readmiss_30d/held_out
preds_df_fp: ${model_run_dir}/eval/readmiss_30d/readmiss_30d.csv

# where to save eval outputs (outside hydra run dir if you want)
#output_root: ${model_run_dir}/eval/${index_time_hash}/
output_root: ${model_run_dir}/eval/readmiss_30d/
do_overwrite: true
do_resume: false
seed: 140799
only_preprocess: false
