defaults:
  - input_encoder: triplet_encoder
  - backbone: triplet_transformer_decoder
  - _self_
_target_: models.everyquery.EveryQueryModule.initialize

projector: 
  mode: supervised_query
  dropout: 0
  
query:
  mode: triplet # stack, triplet
  encod_dim: # will be set automatically based on mode
  embed_dim: 7

backbone:
  n_layers: 2
  nheads: 4
  dropout: 0

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 5.0e-4
  weight_decay: 0.01
  eps: 1.0e-8 # default
  betas: [0.9, 0.999] # default
  amsgrad: false # default
  fused: false # default
  
scheduler:
  _target_: transformers.get_cosine_schedule_with_warmup
  _partial_: true
  num_warmup_steps: ${int_prod:0.1,${.num_training_steps}} # ~10% of training steps
  num_training_steps: ${trainer.max_steps}
  num_cycles: 0.5

max_seq_len: ${data.max_seq_len}
token_dim: 512
vocab_size: ${data.vocab_size}
# get_representations: false
# task_name: ${data.task_name}
batch_size: ${data.dataloader.batch_size}

# compile model for faster training with pytorch 2.0
compile: false
