defaults:
  - input_encoder: triplet_encoder
  - backbone: triplet_transformer_decoder
  - _self_
_target_: models.everyquery.EveryQueryModule.initialize

projector: 
  mode: supervised_query
  dropout: 0
  
query:
  mode: triplet # stack, triplet
  encod_dim: # will be set automatically based on mode
  embed_dim: 7

backbone:
  n_layers: 2
  nheads: 4
  dropout: 0

optimizer:
  _target_: torch.optim.AdamW  
  betas: [0.9, 0.999]
  eps: 1.0e-8  # default 
  amsgrad: false  # default 
  fused: false  # default 
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0

scheduler:
  _target_: transformers.get_cosine_schedule_with_warmup
  _partial_: true
  num_warmup_steps: ${eval:'${trainer.max_steps} * 0.1'} # 10% of training steps
  num_training_steps: ${trainer.max_steps}  # Total steps computed from epochs
  num_cycles: 0.5

max_seq_len: ${data.dataset.max_seq_len}
token_dim: 512
vocab_size: ${data.dataset.vocab_size}
# get_representations: false
# task_name: ${data.dataset.task_name}
batch_size: ${data.dataloader.batch_size}

# compile model for faster training with pytorch 2.0
compile: false
