# @package _global_

defaults:
  - data: everyquery 
  - model: everyquery
  - logger: wandb
  - trainer: ddp
  - paths: default
  - extras: default
  - hydra: default
  - _self_

name: "eval"

seed: 140799

task_name: null

tags:
  - "mgb"
  - "triplet"
  - "supervised"
  - "eval"
  - "zeroshot"

logger:
  wandb:
    tags: ${tags}
    group: "zeroshot"
    project: "EveryQuery"

# passing checkpoint path is necessary for evaluation
ckpt_path: '/storage2/payal/EveryQuery/results/2025-04-14_15-08-39_280969/checkpoints/epoch_037.ckpt' # big mlp categorical model
# ckpt_path: '/storage2/payal/EveryQuery/results/2025-02-11_20-19-05_486757/checkpoints/epoch_030.ckpt' # original categorical model
# ckpt_path: '/storage2/payal/EveryQuery/results/2025-02-10_09-17-58_872984/checkpoints/epoch_029.ckpt' # ecg 0 fixed single supervised 