# @package _global_

defaults:
  - data: everyquery 
  - model: everyquery
  - logger: wandb
  - trainer: ddp
  - paths: default
  - extras: default
  - hydra: default
  - _self_

name: "eval"

seed: 140799

task_name: null

tags:
  - "mgb"
  - "triplet"
  - "supervised"
  - "eval"
  - "zeroshot"

logger:
  wandb:
    tags: ${tags}
    group: "zeroshot"
    project: "EveryQuery"

# passing checkpoint path is necessary for evaluation
ckpt_path: "/home/pac4279/EveryQuery/results/2025-05-26_17-07-50_945117/checkpoints/best_model.ckpt"
