defaults:
  - _self_
  - eval_codes: 

# inputs
model_run_dir: /users/gbk2114/EveryQuery/results/outputs/2025-12-10/17-59-21
index_time_hash: 7573f855c4b050a9d79d57fefd8a139c
task_set_dir: /users/gbk2114/eq_stuff/tasks/eval/tasks_from_index/${index_time_hash}/
ckpt_path: last


eval_codes: [MEDS_DEATH]

# where to save eval outputs (outside hydra run dir if you want)
output_root: ${model_run_dir}/eval/${task_set_name}/${split}/${eval_code_idx}

do_overwrite: false
do_resume: false
seed: 140799
only_preprocess: false
