defaults:
  - _self_

# inputs
model_run_dir: /users/gbk2114/EveryQuery/results/outputs/2025-12-10/17-58-26
task_parent_dir: /users/gbk2114/eq_stuff/tasks/manual
task_set_name: cde742daabc4ddc5e79f29102ea14107
eval_code_idx: 0
split: held_out
ckpt_path: last


# derived paths
task_set_dir: ${task_parent_dir}/${task_set_name}/${split}/${eval_code_idx}
manifest_path: ${task_set_dir}/manifest.parquet
# where to save eval outputs (outside hydra run dir if you want)
output_root: ${model_run_dir}/eval/${task_set_name}/${split}/${eval_code_idx}


do_overwrite: false
do_resume: false
seed: 140799
only_preprocess: false
